services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw # openssl rand -hex 16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: masterkey
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5
  auction-svc:
    image: trycatchlearn/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Http__Url=http://+:80
      - Kestrel__Endpoints__gRPC__Url=http://+:81
      - Kestrel__Endpoints__gRPC__Protocols=Http2
    ports:
      - "7001:80"
      - "7777:81"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  search-svc:
    image: trycatchlearn/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - AuctionSvcUrl=http://auction-svc
      - Meilisearch__Url=http://meilisearch:7700
      - Meilisearch__ApiKey=masterkey
    ports:
      - "7002:80"
    depends_on:
      meilisearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  identity-svc:
    image: trycatchlearn/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
      - IdentityServer__IssuerUri=https://id.carsties.test
      - ClientAppUrl=https://app.carsties.test
      - VIRTUAL_HOST=id.carsties.test
    ports:
      - "5001:80"
    volumes:
      - id_data:/app/keys
    depends_on:
      postgres:
        condition: service_healthy
  gateway-svc:
    image: trycatchlearn/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=api.carsties.test
    ports:
      - "6001:80"
  bid-svc:
    image: trycatchlearn/bid-svc:latest
    build:
      context: .
      dockerfile: src/BidService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=bids
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuctionServiceUrl=http://auction-svc:81
    ports:
      - "7003:80"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  notify-svc:
    image: trycatchlearn/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
    ports:
      - "7004:80"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  web-app:
    image: trycatchlearn/web-app
    build:
      context: ./frontend/web-app
      dockerfile: Dockerfile
    volumes: 
      - /var/lib/web/data
    ports:
      - "3000:3000"
    environment:
      - BETTER_AUTH_SECRET=SDDEu2FOdENiwBLuB62fFeejzFPUkKF8
      - BETTER_AUTH_URL=https://app.carsties.test
      - BASE_API_URL=http://gateway-svc
      - ID_URL_INTERNAL=http://identity-svc
      - VIRTUAL_HOST=app.carsties.test
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./local-deploy/proxy-buffers.conf:/etc/nginx/conf.d/proxy-buffers.conf:ro
      - ./local-deploy/dev-certs:/etc/nginx/certs
volumes:
  postgres_data:
  meilisearch_data:
  rabbitmq_data:
  id_data: