import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/nav/NavBar";
import {Toaster} from "@/components/ui/toast";
import SignalRProvider from "@/contexts/SignalRContext";
import LiveNotifications from "@/contexts/LiveNotifications";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className='bg-muted min-h-screen flex flex-col'>
      <SignalRProvider>
          <NavBar />
          <main className="container mx-auto mt-8 flex flex-1 flex-col">
              {children}
          </main>
          <Toaster />
          <LiveNotifications />
      </SignalRProvider>
      </body>
    </html>
  );
}
