<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="WolverineFx.RabbitMQ" Version="6.25.3" />
      <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.25.5" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
