apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: default
spec:
  parentRefs:
    - name: carsties-gateway
      sectionName: http
      kind: Gateway

  hostnames:
    - id.146.190.200.142.nip.io
    - api.146.190.200.142.nip.io
    - app.146.190.200.142.nip.io

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: identity-route
  namespace: default
spec:
  parentRefs:
    - name: carsties-gateway
      sectionName: https
      kind: Gateway

  hostnames:
    - id.146.190.200.142.nip.io

  rules:
    - backendRefs:
        - name: identity-svc
          namespace: default
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: default
spec:
  parentRefs:
    - name: carsties-gateway
      sectionName: https
      kind: Gateway

  hostnames:
    - api.146.190.200.142.nip.io

  rules:
    - backendRefs:
        - name: gateway-svc
          namespace: default
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-route
  namespace: default
spec:
  parentRefs:
    - name: carsties-gateway
      sectionName: https
      kind: Gateway

  hostnames:
    - app.146.190.200.142.nip.io

  rules:
    - backendRefs:
        - name: web-app
          namespace: default
          port: 3000