apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
  labels:
    app: auction-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-svc
  template:
    metadata:
      name: auction-svc
      labels:
        app: auction-svc
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ["sh", "-c", "until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done"]
        - name: wait-for-rabbitmw
          image: busybox
          command: [ "sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done" ]
      containers:
        - name: auction-svc
          image: trycatchlearn/auction-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 81
              name: grpc
          env:
            - name: RabbitMQ__Host
              value: rabbitmq
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-user
                  name: carsties-secrets
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: carsties-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: carsties-secrets
            - name: ConnectionStrings__DefaultConnection
              value: Server=postgres:5432;User Id=postgres;Password=$(POSTGRES_PASSWORD);Database=auctions
            - name: IdentityServiceUrl
              value: http://identity-svc
            - name: Kestrel__Endpoints__Http__Url
              value: http://+:80
            - name: Kestrel__Endpoints__gRPC__Url
              value: http://+:81
            - name: Kestrel__Endpoints__gRPC__Protocols
              value: Http2
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auction-svc
spec:
  selector:
    app: auction-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - port: 81
      targetPort: 81
      name: grpc
  type: ClusterIP
    
      