name: WebApp

on:
  workflow_dispatch:
#  push trigger disabled following end of course
#  push:
#    branches: [main]
#    paths:
#      - "frontend/web-app/**"
#      - "k8s/services/web-app.yml"
#      - ".github/workflows/web-app.yml"
#      - ".github/workflows/deploy.yml"

concurrency:
  group: web-app-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/deploy.yml
    with:
      image: web-app
      dockerfile: frontend/web-app/Dockerfile
      context: frontend/web-app
    secrets: inherit